import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import MuiProvider from "@/provider/MuiProvider";
import { DndProvider } from "@/provider/DndProvider";


const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <MuiProvider>
          <DndProvider>{children}</DndProvider>
        </MuiProvider>
      </body>
    </html>
  );
}
